update rust agent
Zondax/icp-client-cpp pull request #5
Opened 2023-05-26 16:16 UTC by chcmedeiros

:link: [zboto Link](https://app.clickup.com/t/86781rznx)

2023-05-26 20:49 UTC, neithanmo requested changes
Getting good!!!! 

just a few key points:
- do not call `unwrap()/expect() `unless it is safe to, in code from C.
- replace: `x.to_string() + '\0'`, with `CString::new().ok()?.into_bytes();`
- Add a note in lib-agent-c documentation for all functions that take ownership of the memory.
- I did not see candid.c/h in lib-agent-c/src/ but there are for agent, helper, and identity modules.
- try to use a memory leak profiler to ensure memory is being released, there are a few places where this still happens. valgrind is a good tool, for example, to run Valgrind profiler on candid example:
`valgrind --leak-check=full ./candid`

2023-05-26 20:49 UTC, neithanmo commented on ic-agent-wrapper/src/candid/mod.rs
> +/// @brief Create IDLArgs from an IDLValue Array(C)/Vector(Rust)
Add a note saying that this function takes ownership of each IDLValue in the array, so users do not try to use it after this call.

2023-05-26 20:49 UTC, neithanmo commented on ic-agent-wrapper/src/candid/mod.rs
> +/// @param elems Pointer to array of IDLValues, take in account rust will take
Good, you added in the doc here that this function takes ownership, please do the same in other similar functions.

2023-05-26 20:49 UTC, neithanmo commented on ic-agent-wrapper/src/candid/mod.rs
> +        let _ = Box::into_raw(boxed);
why this?  why are we leaking this memory? boxed is allocated, `into_raw(boxed)` would make the compiler forget about it and never free it.

2023-05-26 20:49 UTC, neithanmo commented on ic-agent-wrapper/src/candid/mod.rs
> +        let val = boxed.deref().clone();
just a suggestion:
`let val = *boxed; // and that is equivalent to .defer().clone(); `
just in case we do not need boxed anymore.

2023-05-26 20:49 UTC, neithanmo commented on ic-agent-wrapper/src/lib.rs
> +pub extern "C" fn cidlval_vec_destroy(_ptr: Option<Box<CIDLValuesVec>>) {}
who frees the memory pointed by each *const IDLValue in Vector? 
this destructor as it is now, is leaking memory. 
In candid/mod.rs:855 you have:
```
[no_mangle]
pub extern "C" fn vec_from_idl_value(ptr: &IDLValue) -> Option<Box<CIDLValuesVec>> {
    let r = {
        let s = match ptr {
            IDLValue::Vec(v) => v.to_owned(),
            _ => return None,
        };

        let mut ptrs = Vec::new();

        for idl_value in s {
            let boxed = Box::new(idl_value); // allocates idl_value
            let ptr = Box::into_raw(boxed); // get pointer, memory remains allocated

            ptrs.push(ptr as *const IDLValue); // push pointer to memory
        }

        ptrs
    };

    Some(Box::new(CIDLValuesVec { data: r }))
}
```
so as you see, we need to call idl_value_destroy on each pointer in CIDLValuesVec, when it gets destroyed.

2023-05-30 13:17 UTC, neithanmo approved these changes

2023-05-30 18:30 UTC, ftheirs commented on lib-agent-c/src/helper.c
> +#include "../inc/helper.h"
nit: probably we can include `../inc` folder in CMakeList and we avoid having relative paths for including headers

2023-05-31 12:48 UTC, merged